# Generated by Django 3.2.8 on 2022-05-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='scores',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='scores',
            old_name='subjects',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='scores',
            old_name='terms',
            new_name='term',
        ),
        migrations.AlterField(
            model_name='scores',
            name='type_of_score',
            field=models.CharField(choices=[('Exam', 'Exam'), ('Test', 'Test'), ('Assignment', 'Assignment')], max_length=30),
        ),
    ]
