# Generated by Django 3.2.8 on 2022-05-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_alter_scores_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='score',
            field=models.IntegerField(),
        ),
    ]
