# Generated by Django 3.2.8 on 2022-05-14 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_subject_term_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionYearModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_start_year', models.DateField()),
                ('session_end_year', models.DateField()),
                ('term_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_app.term')),
            ],
        ),
    ]
