# Generated by Django 3.2.8 on 2022-05-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_sessionyearmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_id',
            new_name='s_class',
        ),
    ]
